"""Add last_login column to user table

Revision ID: d3a5aa8f46ac
Revises: fcd66f3cdbe1
Create Date: 2024-09-17 13:07:11.748339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a5aa8f46ac'
down_revision = 'fcd66f3cdbe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_study_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_study_time')
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###
